[build]
  publish = "."
  command = ""

[build.environment]
  NODE_VERSION = "18"

[[headers]]
  for = "/*"
  [headers.values]
    X-Frame-Options = "ALLOW-FROM https://telegram.org"
    Content-Security-Policy = "frame-ancestors 'self' https://telegram.org"
    Cache-Control = "public, max-age=0, must-revalidate"

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
